import a from '/assets/images/books/86_light_novel.jpg'
import b from '/assets/images/books/attack_on_titan_cover.jpg'
import c from '/assets/images/books/beyond_journeys_end_cover.jpg'
import d from '/assets/images/books/vinland_saga_cover.jpg'
import e from '/assets/images/books/violet_evergarden_cover.jpg'
